# Generated by Django 3.2.3 on 2023-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('pub_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jewerly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('pub_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JewForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('pub_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Сhain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('pub_date',),
                'abstract': False,
            },
        ),
    ]
