# Generated by Django 3.2.3 on 2023-11-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewerly',
            name='chain',
            field=models.ForeignKey(default='45', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='chain', to='cards.сhain', verbose_name='Длина цепочки'),
        ),
        migrations.AddField(
            model_name='jewerly',
            name='description',
            field=models.TextField(default='', verbose_name='Описание украшения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewerly',
            name='length',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Длина украшения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewerly',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название украшения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewerly',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена украшения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewerly',
            name='width',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ширина украшения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewform',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название формы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewform',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='Слаг формы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сhain',
            name='color',
            field=models.CharField(default='Серебряный', max_length=200, verbose_name='Цвет цепочки'),
        ),
        migrations.AddField(
            model_name='сhain',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание цепочки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сhain',
            name='length',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Длина цепочки'),
            preserve_default=False,
        ),
    ]
