# Generated by Django 3.2.3 on 2023-11-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20231105_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сhain',
            name='description',
        ),
    ]
