# Generated by Django 3.2.3 on 2023-11-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20231124_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhain',
            name='length',
            field=models.CharField(default='45', max_length=200, verbose_name='Длина цепочки'),
        ),
    ]
